
server:
  port: 8088


spring:
  datasource:
    name: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.2.86:3306/fjt_test?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2b8
    username: devfocsdb3
    password: devfocsdb3
    # 最大上传单个文件大小：默认1M

  servlet:
    multipart:
      max-file-size: 1024MB
    # 最大上传多个文件大小 ：默认10M
      max-request-size: 1024MB


mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-cas: true
    call-setters-on-nulls: true
    cache-enabled: true
  type-aliases-package: com.example.demo.entity
